# Generated by Django 2.0.3 on 2023-03-22 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0011_auto_20180403_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='img',
            field=models.ImageField(default='core/avatar/profile1.jpg', upload_to='core/avatar'),
        ),
    ]
